sudo: false
language: node_js
env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g npm@5.2.0  # Do not bump until https://github.com/npm/npm/issues/17858 is fixed
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - ./travis-testcafe.sh

after_success:
  - tools/docker-build.sh
